kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
        name: grant-stage
        namespace: eric-stage
subjects:
        - kind: ServiceAccount
          name: pipeline
          namespace: eric-demo
roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
