apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-dev-deployment
spec:
  params:
    - name: appName
      type: string
    - name: devProject
      type: string
  steps:
    - args:
        - >-
          echo Waiting for deployment to $(inputs.params.devProject);
          oc wait --for condition=available --timeout=600s deployment/$(inputs.params.appName) -n $(inputs.params.devProject);
          echo Deployment completed
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: wait-for-deployment
      resources: {}
