apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-staging-deployment
spec:
  params:
    - name: appName
      type: string
    - name: stageProject
      type: string
  steps:
    - args:
        - >-
          echo Checking pods of $(inputs.params.appName);

          while true; do pods=$(oc get pods -l
          deployment=$(inputs.params.appName) -n $(inputs.params.stageProject)
          ); if [ -z "$pods" ];then echo "Pods not created yet"; sleep 20;
          continue;fi; pod_status=$(oc get pods -l
          deployment=$(inputs.params.appName) -n $(inputs.params.stageProject) |
          awk 'FNR>1 {print $3}'); echo "Pod status: $pod_status";  if ! grep
          -qv 'Running'<<<"$pod_status";then echo 'All pods ready';break;else
          sleep 10;fi; done;    route=$(oc get route books | awk 'FNR==2 {print
          $2}'); echo "Deployment to Staging env is complete. Access at
          http://$route";
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: ''
      resources: {}
