apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-staging-deployment
spec:
  params:
    - name: appName
      type: string
    - name: stageProject
      type: string
  steps:
    - args:
        - >-
          echo Waiting for deployment to staging; 
          oc wait --for condition=available --timeout=600s deployment/$(inputs.params.appName) -n $(inputs.params.stageProject);   
          route=$(oc get route books | awk 'FNR==2 {print
          $2}'); echo "Deployment to Staging env is complete. Access at
          http://$route";
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: ''
      resources: {}
